var products = [
    {
        name: 'Fair Isle Fleece Shep Shirt',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dweca1c6da/images/2018/1O000027_976_OF_F.jpg?sw=1184&sh=1410&sm=cut',
        price: 135,
        description: "Apres ski! Go Nordic with a men's Shep Shirt that takes the classic pattern to a whole new level of fun.",
    },
    {
        name: 'Stretch Breaker Pants',
        imageUrl: 'https://cdn.shopify.com/s/files/1/2723/2164/products/vineyard-vines-stretch-breaker-pants-nocturne-3219025952810_1024x1024@2x.jpg?v=1525972423',
        price: 98,
        description: "Stretch your wardrobe! With a comfortable stretch in the weave and colors for every day of the week, these will be your go-to men’s pants.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Palm Beach Cotton-Cashmere 1/4-Zip Sweater',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw1d52c31f/images/2018/1E0376_025_OF_F.jpg?sw=657&sh=782&sm=cut',
        price: 138,
        description: "Zip-up warmth! Luxuriously soft, our quarter-zip men's sweater...with cashmere in the blend...elevates your style.",
    },
    {
        name: '9 Inch Stretch Breaker Shorts',
        imageUrl: 'https://cdnd.lystit.com/photos/vineyardvines/7fee0794/vineyard-vines-Sea-Urchin-9-Inch-Stretch-Breaker-Shorts.jpeg',
        price: 98,
        description: "Summer essential! In more colors than a rainbow, our men’s shorts, with their comfortable stretch, will be your go-to choice for summer.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Solid Edgartown Polo',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw69a75e33/images/2018/1K2298.996.a.zoom.jpg?sw=657&sh=782&sm=cut',
        price: 79,
        description: "Ahoy! Our NEW polo style is named after one of our favorite places on the Vineyard. Take a little piece of the summer with you wherever you are!.",
    },
    {
        name: 'Carleton Gingham Classic Stretch Tucker Shirt',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw3f46da47/images/2018/1W3569_786_OF_F.jpg?sw=657&sh=782&sm=cut',
        price: 98,
        description: "A gingham a day! When a pattern looks this good, you'll want our men's classic-fit sport shirt in every color.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Heritage Terry Jogger Pants',
        imageUrl: 'https://cdnb.lystit.com/photos/zappos/4be32072/vineyard-vines-Deep-Bay-Heritage-Terry-Jogger-deep-Bay-Mens-Casual-Pants.jpeg',
        price: 85,
        description: "Lux joggers! These men's jogger pants are so super soft and comfy to wear, you'll have a hard time giving them up for laundering.",
    },
    {
        name: 'Customized Canvas Hat',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw5a6bb59b/images/2017/monogram/1A6017/34/1A6017.34.d.zoom.jpg?sw=657&sh=782&sm=cut',
        price: 28,
        description: "A traditional six panel baseball cap with an adjustable strap",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Tech Fleece Harbor Vest',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw919df7c8/images/2018/1O0310_410_OF_F.jpg?sw=657&sh=782&sm=cut',
        price: 98,
        description: "Tech it up a notch! This warm men's vest fends off wintry breezes and keeps all your essentials securely close at hand in its zip pockets.",
    },
    {
        name: 'Woody & Ski Whale Boxers',
        imageUrl: 'https://cdnd.lystit.com/1200/630/tr/photos/vineyardvines/f0b83ccf/vineyard-vines-Calypso-Red-Woody-Ski-Whale-Boxers.jpeg',
        price: 24,
        description: "Snow-bound! Your thoughts may be on downhill, but your day will be all uphill with these comfy men's boxers.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Octopus Printed Tie',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw07cff8f3/images/2018/1T000160_317_LD_F.jpg?sw=657&sh=782&sm=cut',
        price: 85,
        description: "100% silk printed tie",
    },
    {
        name: 'Canvas Duffle Bag',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw9c782057/images/2016/2A2727.002.a.zoom.jpg?sw=657&sh=782&sm=cut',
        price: 79,
        description: "Gear up for fall! This spacious men’s duffle bag can be stuffed full of everything you need for a day on the water or in the gym.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Woody & Tree Dog Collar',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dwec0ff451/images/2018/5A000126_634_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 28,
        description: "Festive Fido! Our dog collar is a fun way to include the family pet in the merriment.",
    },
    {
        name: 'Mens Blackwatch Holiday Slippers',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw6fad5032/images/2018/1Z000005_002_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 98,
        description: "Slip into the holidays! Get festive from head to toe by adding a pair of men's slippers all dressed up for the big day- and eve.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Blackwatch Merino Scarf',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dwe5404511/images/2018/1A000014_342_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 78,
        description: "Holiday-ready! Our festive tartan men's scarf is perfect when caroling your way around the neighborhood on a cold winter's night.",
    },
    {
        name: 'Under The Water Chappy Trunks',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw8a391e85/images/2018/1M0646_461_OF_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 89,
        description: "Side and back pockets",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Long-Sleeve Ski Goggles Pocket T-Shirt',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dwdd927938/images/2018/1V5161_039_LD_B.jpg?sw=1680&sh=2000&sm=cut',
        price: 48,
        description: "What a view! We're all in for a day on the slopes as you can see clearly by this men's long-sleeve T-shirt.",
    },
    {
        name: 'Performance Blazer',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dwe14cfedd/images/2018/1J0155.410.a.zoom.jpg?sw=1680&sh=2000&sm=cut',
        price: 495,
        description: "Yacht worthy! Whether breaking a bottle over the bow of a new boat or racing to make an international connection, our men's sport coat does it with comfort and style.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'vineyard vines x Smathers & Branson Classic Whale Needlepoint Belt',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw03166c61/images/2018/1B000033_946_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 165,
        description: "New additions to our collaboration with our friends at Smathers & Branson",
    },
    {
        name: 'Crossed Skis Icon Socks',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dwda4141f8/images/2018/1S000004_786_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 19,
        description: "As soft as powdered snow! Off the slopes, enjoy the comfort of our men's socks that pay tribute to your favorite winter sport.",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Monogrammed Sailboat Sketch iPhone 7/8 Case',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw1518a3f5/images/2018/5A000075_906_LD_B.jpg?sw=1680&sh=2000&sm=cut',
        price: 45,
        description: "Fits your iPhone 7/8",
    },
    {
        name: 'Fishing Sticker Pack',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw1b16dece/images/2018/5A000092_998_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 13,
        description: "Paper envelope includes 6 whale fill stickers",
        //detailsFile: 'myFile.html',
    },
    {
        name: 'Whale Ornament',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dw6d5bcb19/images/2017/5A7530.650.a.zoom.jpg?sw=1680&sh=2000&sm=cut',
        price: 48,
        description: "Delicate, detailed, high quality glass ornament ",
    },
    {
        name: 'Yeti 30 Oz Rambler',
        imageUrl: 'https://www.vineyardvines.com/dw/image/v2/AAHW_PRD/on/demandware.static/-/Sites-vineyardvines-master/default/dwaac749e1/images/2018/5A000093_410_LD_F.jpg?sw=1680&sh=2000&sm=cut',
        price: 50,
        description: "Stainless steel construction with a double wall vacuum insulation",
        //detailsFile: 'myFile.html',
    },
];